### ISSUE TITLE
Cleanup non-essential files from QuickStart project...

### ISSUE THREAD

**Issue by linuxwebexpert** [bijanmmarkes/vta-challenge#1]
Nice work on getting a useful map application together...

My only real comment is this was a little confusing at first, since the non-essential files hadn't been removed yet per the instructions from the Angular2 QuickStart - https://github.com/angular/quickstart

If you get a moment, please sanitize and clean non essential files with `git rm --cached filenamehere`

**Comment by bijanmmarkes** [comment]
Thanks, I have removed all the non-essential files they provided in the .txt document.
